vich_uploader:
    db_driver: orm

    metadata:
        type: attribute

    mappings:
        accommodations:
            uri_prefix: /images/accommodations
            upload_destination: '%kernel.project_dir%/public/images/accommodations'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
